#!/bin/bash

java -Xmx5g -cp ${WEKA_HOME}/weka.jar weka.Run \
     .Dl4jMlpClassifier \
	 -S "42" \
	 -normalization "Standardize training data" \
	 -iterator "weka.dl4j.iterators.instance.ImageInstanceIterator -height 28 -imagesLocation ../wekaDeeplearning4jCore/src/test/resources/nominal/mnist-minimal -numChannels 1 -bs 256 -width 28" \
	 -layer "weka.dl4j.layers.ConvolutionLayer -nFilters 32 -activation \"weka.dl4j.activations.ActivationIdentity \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -mode Truncate -cudnnAlgoMode PREFER_FASTEST -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -kernelSizeX 3 -kernelSizeY 3 -L1 NaN -L2 NaN -name \"Conv-layer 1\" -lr NaN -momentum NaN -paddingX 0 -paddingY 0 -rho NaN -rmsDecay NaN -strideX 1 -strideY 1" \
	 -layer "weka.dl4j.layers.BatchNormalization -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -beta 0.0 -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -decay 0.9 -dropout 0.0 -eps 1.0E-5 -epsilon NaN -gamma 1.0 -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Batch normalization layer 1\" -lr NaN -beta false -momentum NaN -noMinibatch false -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.ConvolutionLayer -nFilters 32 -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -mode Truncate -cudnnAlgoMode PREFER_FASTEST -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -kernelSizeX 3 -kernelSizeY 3 -L1 NaN -L2 NaN -name \"Convolution layer 1\" -lr NaN -momentum NaN -paddingX 0 -paddingY 0 -rho NaN -rmsDecay NaN -strideX 1 -strideY 1" \
	 -layer "weka.dl4j.layers.BatchNormalization -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -beta 0.0 -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -decay 0.9 -dropout 0.0 -eps 1.0E-5 -epsilon NaN -gamma 1.0 -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Batch normalization layer 2\" -lr NaN -beta false -momentum NaN -noMinibatch false -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.SubsamplingLayer -mode Truncate -dropout 0.0 -eps 1.0E-8 -kernelSizeX 2 -kernelSizeY 2 -name Pool1 -paddingX 0 -paddingY 0 -pnorm 1 -poolingType MAX -strideX 2 -strideY 2" \
	 -layer "weka.dl4j.layers.ConvolutionLayer -nFilters 64 -activation \"weka.dl4j.activations.ActivationIdentity \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -mode Truncate -cudnnAlgoMode PREFER_FASTEST -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -kernelSizeX 3 -kernelSizeY 3 -L1 NaN -L2 NaN -name \"Convolution layer 2\" -lr NaN -momentum NaN -paddingX 0 -paddingY 0 -rho NaN -rmsDecay NaN -strideX 1 -strideY 1" \
	 -layer "weka.dl4j.layers.BatchNormalization -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -beta 0.0 -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -decay 0.9 -dropout 0.0 -eps 1.0E-5 -epsilon NaN -gamma 1.0 -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Batch normalization layer 3\" -lr NaN -beta false -momentum NaN -noMinibatch false -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.ConvolutionLayer -nFilters 64 -activation \"weka.dl4j.activations.ActivationIdentity \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -mode Truncate -cudnnAlgoMode PREFER_FASTEST -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -kernelSizeX 3 -kernelSizeY 3 -L1 NaN -L2 NaN -name \"Convolution layer 3\" -lr NaN -momentum NaN -paddingX 0 -paddingY 0 -rho NaN -rmsDecay NaN -strideX 1 -strideY 1" \
	 -layer "weka.dl4j.layers.BatchNormalization -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -beta 0.0 -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -decay 0.9 -dropout 0.0 -eps 1.0E-5 -epsilon NaN -gamma 1.0 -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Batch normalization layer 4\" -lr NaN -beta false -momentum NaN -noMinibatch false -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.SubsamplingLayer -mode Truncate -dropout 0.0 -eps 1.0E-8 -kernelSizeX 2 -kernelSizeY 2 -name \"Subsampling layer\" -paddingX 0 -paddingY 0 -pnorm 1 -poolingType MAX -strideX 2 -strideY 2" \
	 -layer "weka.dl4j.layers.DenseLayer -nOut 512 -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Hidden layer\" -lr NaN -momentum NaN -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.BatchNormalization -activation \"weka.dl4j.activations.ActivationReLU \" -adamMeanDecay NaN -adamVarDecay NaN -beta 0.0 -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -decay 0.9 -dropout 0.2 -eps 1.0E-5 -epsilon NaN -gamma 1.0 -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Batch normalization layer 5\" -lr NaN -beta false -momentum NaN -noMinibatch false -rho NaN -rmsDecay NaN" \
	 -layer "weka.dl4j.layers.OutputLayer -activation \"weka.dl4j.activations.ActivationSoftmax \" -adamMeanDecay NaN -adamVarDecay NaN -biasInit NaN -l1Bias 0.0 -l2Bias 0.0 -blr NaN -dropout 0.0 -epsilon NaN -gradientNormalization None -gradNormThreshold 1.0 -L1 NaN -L2 NaN -name \"Output layer\" -lr NaN -lossFn \"weka.dl4j.lossfunctions.LossMCXENT \" -momentum NaN -rho NaN -rmsDecay NaN" \
	 -logFile "/home/slang/IdeaProjects/wekaDeeplearning4j/wekaDeeplearning4jCore" \
	 -config "weka.dl4j.NeuralNetConfiguration -l1 NaN -l2 NaN -leakyreluAlpha 0.01 -lr 0.1 -learningRatePolicy None -lrPolicyDecayRate NaN -lrPolicyPower NaN -lrPolicySteps NaN -maxNumLineSearchIterations 5 -minimize -numIterations 1 -algorithm STOCHASTIC_GRADIENT_DESCENT -stepFunction \"weka.dl4j.stepfunctions.NegativeGradientStepFunction \" -updater ADAM -useRegularization -weightInit XAVIER" \
     -numEpochs 10 \
     -t ../wekaDeeplearning4jCore/datasets/nominal/mnist.meta.minimal.arff \
     -no-cv
